---
title: "In Class Exercise 4"
description: |
  A new article created using the Distill format.
author:
  - name: Ong Zhi Rong Jordan
    url: https://example.com/norajones
    affiliation: Spacely Sprockets
    affiliation_url: https://example.com/spacelysprokets
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      eval = TRUE,
                      warning = FALSE,
                      message = FALSE, 
                      fig.retina = 3)
```

# Getting Started

## Setting up R Packages

To start with [ggstatsplot](https://indrajeetpatil.github.io/ggstatsplot/) and tidyverse packages will be launched using library ().

```{r}

packages = c('ggstatsplot','tidyverse')
for (p in packages){
  if(!require(p, character.only = T)){
    install.packages(p)
  }
}

```



## Importing data

```{r}
exam <- read_csv("data/Exam_data.csv")

```

## Working with ggstatsplot

### Anova Test

``` {r}

set.seed(123)

ggbetweenstats(
  data = exam,
  x = RACE, 
  y = ENGLISH,
  type = "bayes"
)

```





